application:
  subdomain: cfui
  background_task: true
  public_path:
    - /

  upstreams:
    - location: /
      backend: http://host.lzcapp:14333/

services:
  cfui:
    network_mode: host
    user: root
    # czyt/cfui:v0.2.13
    image: registry.lazycat.cloud/czyt/czyt/cfui:1509dbb6c4ac87d8
    binds:
      - /lzcapp/var/data:/app/data
      - /lzcapp/var/logs:/app/logs
    environment:
      - BIND_HOST=
      - PORT=14333
      - DATA_DIR=/app/data
